FROM node:16-bullseye-slim as builder
#FROM node:16.17.0-bullseye-slim as builder

ARG COMMIT_SHA
ENV COMMIT_SHA=${COMMIT_SHA}
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT}
ARG VITE_REACT_APP_DEPLOY_VERSION
ENV VITE_REACT_APP_DEPLOY_VERSION=${VITE_REACT_APP_DEPLOY_VERSION}
ARG VITE_REACT_APP_DEPLOY_ENVIRONMENT
ENV VITE_REACT_APP_DEPLOY_ENVIRONMENT=${VITE_REACT_APP_DEPLOY_ENVIRONMENT}
ARG VITE_REACT_APP_ANALYTICS_KEY
ENV VITE_REACT_APP_ANALYTICS_KEY=${VITE_REACT_APP_ANALYTICS_KEY}
ARG VITE_IPFS_API_KEY
ENV VITE_IPFS_API_KEY=${VITE_IPFS_API_KEY}
ARG VITE_ETHERSCAN_API_KEY
ENV VITE_ETHERSCAN_API_KEY=${VITE_ETHERSCAN_API_KEY}
ARG NODE_OPTIONS
ENV NODE_OPTIONS=${NODE_OPTIONS}

RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

## Install deps from parent folder
WORKDIR /app
COPY package*.json .
COPY yarn.lock .
RUN yarn
COPY . .

## Install deps, build and link ui-components
WORKDIR /app/packages/ui-components
RUN yarn install --pure-lockfile 
RUN yarn build 
RUN yarn link

## Install deps web-app
WORKDIR /app/packages/web-app
RUN yarn install --pure-lockfile

## Link web-app to ui-components
RUN yarn link @aragon/ui-components

## Build web-app to generate static site in /dist
RUN yarn build

## New stage to server static site from Caddy
FROM caddy:2.6.4-alpine
COPY --from=builder /app/caddyfile.webapp.dev /etc/caddy/Caddyfile
COPY --from=builder /app/packages/web-app/dist /website
EXPOSE 9080
